name = "SCP-Regalis's Containment Breach Assets"
prefix = "RegalisSCP_CB"
author = "Sanuki357"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_RegalisSCP_CB_ca.paa",
]

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip RegalisSCP_CB_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"