name = "SCP-Regalis's Containment Breach Assets";
author = "Sanuki357";
//picture = "\SCP_CB\SCP_CB_Logo.paa"; 
logo = "z\logo_RegalisSCP_CB_ca.paa";
logoSmall = "z\logo_RegalisSCP_CB_ca.paa"; // SCP_CB_Logo.paa
logoOver = "z\SCP_CB_LogoGlow.paa";
action = "https://community.bistudio.com/wiki/Mod_Presentation";
tooltipOwned = "SCP-CB";
dlcColor[] = {	0.5, 0.5, 0.5, 1};
overview = "Adds stuff";
hideName = 0;
hidePicture = 0;