name = "SCP-Regalis's Containment Breach Assets";
author = "Sanuki357";
picture = "logo_RegalisSCP_CB_ca.paa"; 
logo = "logo_RegalisSCP_CB_ca.paa";
logoSmall = "logo_RegalisSCP_CB_ca.paa"; // SCP_CB_Logo.paa
logoOver = "SCP_CB_LogoGlow.paa";
action = "https://github.com/Sanuki357/Regalis-s-SCP-CB-Assets-for-Arma-3";
tooltipOwned = "SCP-CB";
dlcColor[] = {	0.5, 0.5, 0.5, 1};
overview = "Adds stuff";
hideName = 0;
hidePicture = 0;